### PR TITLE
s2i enabled docker image

### PR DESCRIPTION
**Pull request by rpitonak**
- image can be used to build nodejs applications on Fedora
- documentation for s2i

### CODE REVIEW

**Comment by eliskasl** [comment]
A new app builds fine, but usage displayed at "docker run" needs some fixing:

starting container process caused "exec: \"usage\": executable file not found in $PATH"

**Comment by rpitonak** [comment]
It should be fixed now.

**Comment by eliskasl** [comment]
LGTM. @kasicka do you want to have a look too?

**Comment by kasicka** [comment]
There should be a note in README that Node 8 isn't available yet, otherwise LGTM.

**Comment by rpitonak** [comment]
@kasicka good point, now it should be ok.

**Comment by TomasTomecek** [comment]
LGTM, well done (can't want to see green fields in CI so we're sure it works well)

**Pull request merged**
